name: 'GitHub Pages Quick Index'
description: 'A minimal GitHub Action that generates a simple index.html to quickly access test reports generated in workflows'
author: 'ykmr1224'
inputs:
  reports-path:
    description: 'Path to the directory containing HTML reports'
    required: false
    default: './reports'
  output-file:
    description: 'Path where the generated index.html will be saved'
    required: false
    default: './index.html'
  file-filter:
    description: 'Regex pattern to filter HTML files (e.g., "test.*\\.html$" to match test files)'
    required: false
    default: ''
outputs:
  index-path:
    description: 'Path to the generated index.html file'
  html-files:
    description: 'JSON array of found HTML file paths'
  file-count:
    description: 'Number of HTML files found'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'file-text'
  color: 'blue'
